version: '3.8'

services: 
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
        volumes: 
            # - D:\RabbitMQ:/var/lib/rabbitmq
            - /path/to/rabbitmq:/var/lib/rabbitmq
        environment: 
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        networks:
            - rmqnet

networks: 
    rmqnet:
        name: rmqnet
        driver: bridge